# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

# Theme
set -g @themepack 'powerline/default/blue'

# Mouse scroll
set-option -g mouse on

# True color support
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Reduce escape time (important for vim)
set -sg escape-time 10

# Start window and pane index at 1
set -g base-index 1
setw -g pane-base-index 1

# Plugin manager (keep last)
run '~/.tmux/plugins/tpm/tpm'
