#
# PATH
#
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

#
# Oh My Zsh
#
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"

# Hide user@hostname on local machine
DEFAULT_USER="$USER"
prompt_context(){}

plugins=(git scala sbt fzf)

source $ZSH/oh-my-zsh.sh

#
# Locale
#
export LANG=en_US.UTF-8

#
# Editor
#
export EDITOR="vim"

#
# Java
#
export JAVA_HOME="/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
eval "$(jenv init -)"

#
# History
#
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history

#
# Shell behaviour
#
setopt auto_cd
setopt correct_all
setopt auto_list
setopt auto_menu
setopt always_to_end

#
# FZF
#
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

#
# Aliases
#
alias zshconfig="vim ~/.zshrc"
alias scala="scala -Dscala.color=true"

# Docker
alias dka='docker ps -a'
alias dkkill='docker ps -q | xargs -r docker kill'
alias dkrm='docker ps -a -q | xargs -r docker rm'
alias dkrmi='docker images -q | xargs -r docker rmi'
alias dkc='dkkill; dkrm'

#
# Syntax highlighting (brew-prefix aware for Intel and Apple Silicon)
#
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

#
# Agents
#
export OPENCODE_API_KEY=""

#
# PI
#
export REVDIFF_THEME="solarized-dark"
